// Provides a selection of topologically distinct connected graphs for testing and demonstration purpose
let graphs = {
  ONE_NO_ATTACK: { '0': [] },
  ONE_SELF_ATTACKED: { '0': ['0'] },
  TWO_ASYMMETRIC_ATTACK: { '0': [], '1': ['0'] },
  TWO_ASYMMETRIC_ATTACK_SELF_ATTACK_TARGET: { '0': [], '1': ['0','1'] },
  TWO_ASYMMETRIC_ATTACK_SELF_ATTACK_ATTACKER: { '0': ['0'], '1': ['0'] },
  TWO_SYMMETRIC_ATTACK: { '0': ['1'], '1': ['0']},
  TWO_SYMMETRIC_ATTACK_SELF_ATTACK_ONE: { '0': ['1','0'], '1': ['0']},
  TWO_SYMMETRIC_ATTACK_SELF_ATTACK_BOTH: { '0': ['1','0'], '1': ['0','1']},
  THREE_CHAIN: { '0': [], '1': ['0'], '2': ['1']},
  THREE_CHAIN_SELF_ATTACK_TOP: { '0': ['0'], '1': ['0'], '2': ['1']},
  THREE_CHAIN_SELF_ATTACK_MIDDLE: { '0': [], '1': ['0','1'], '2': ['1']},
  THREE_CHAIN_SELF_ATTACK_TOP_AND_MIDDLE: { '0': ['0'], '1': ['0','1'], '2': ['1']},
  THREE_CHAIN_SELF_ATTACK_BOTTOM: { '0': [], '1': ['0'], '2': ['1','2']},
  THREE_CHAIN_SELF_ATTACK_MIDDLE_AND_BOTTOM: { '0': [], '1': ['0','1'], '2': ['1','2']},
  THREE_CHAIN_SELF_ATTACK_TOP_AND_BOTTOM: { '0': ['0'], '1': ['0'], '2': ['1','2']},
  THREE_CHAIN_SELF_ATTACK_ALL: { '0': ['0'], '1': ['0','1'], '2': ['1','2']},
  THREE_CHAIN_DEFENSE_AT_TOP: { '0': ['1'], '1': ['0'], '2':['1']},
  THREE_CHAIN_DEFENSE_AT_TOP_SELF_ATTACK_TOP: { '0': ['1','0'], '1': ['0'], '2':['1']},
  THREE_CHAIN_DEFENSE_AT_TOP_SELF_ATTACK_MIDDLE: { '0': ['1'], '1': ['0','1'], '2':['1']},
  THREE_CHAIN_DEFENSE_AT_TOP_SELF_ATTACK_BOTTOM: { '0': ['1'], '1': ['0'], '2':['1','2']},
  THREE_CHAIN_DEFENSE_AT_TOP_SELF_ATTACK_TOP_AND_MIDDLE: { '0': ['1','0'], '1': ['0','1'], '2':['1']},
  THREE_CHAIN_DEFENSE_AT_TOP_SELF_ATTACK_TOP_AND_BOTTOM: { '0': ['1','0'], '1': ['0'], '2':['1','2']},
  THREE_CHAIN_DEFENSE_AT_TOP_SELF_ATTACK_MIDDLE_AND_BOTTOM: { '0': ['1','0'], '1': ['0','1'], '2':['1','2']},
  THREE_CHAIN_DEFENSE_AT_BOTTOM: { '0': [], '1': ['0', '2'], '2':['1']},
  THREE_CHAIN_DEFENSE_AT_BOTTOM_SELF_ATTACK_TOP: { '0': ['0'], '1': ['0', '2'], '2':['1']},
  THREE_CHAIN_DEFENSE_AT_BOTTOM_SELF_ATTACK_MIDDLE: { '0': [], '1': ['0', '1','2'], '2':['1']},
  THREE_CHAIN_DEFENSE_AT_BOTTOM_SELF_ATTACK_BOTTOM: { '0': [], '1': ['0', '2'], '2':['1','2']},
  THREE_CHAIN_DEFENSE_AT_BOTTOM_SELF_ATTACK_TOP_AND_MIDDLE: { '0': ['0'], '1': ['0', '1','2'], '2':['1']},
  THREE_CHAIN_DEFENSE_AT_BOTTOM_SELF_ATTACK_TOP_AND_BOTTOM: { '0': ['0'], '1': ['0', '2'], '2':['1','2']},
  THREE_CHAIN_DEFENSE_AT_BOTTOM_SELF_ATTACK_MIDDLE_AND_BOTTOM: { '0': ['0'], '1': ['0', '1','2'], '2':['1','2']},
  THREE_CYCLE: { '0': ['2'], '1': ['0'], '2':['1']},
  THREE_CYCLE_ONE_SELF_ATTACK: { '0': ['2','0'], '1': ['0'], '2':['1']},
  THREE_CYCLE_TWO_SELF_ATTACKS: { '0': ['2','0'], '1': ['0','1'], '2':['1']},
  THREE_CYCLE_ALL_SELF_ATTACKING: { '0': ['2','0'], '1': ['0','1'], '2':['1','2']},
  THREE_CYCLE_ONE_DEFENSE: { '0': ['2'], '1': ['0'], '2':['1','0']},
  THREE_CYCLE_ONE_DEFENSE_SELF_ATTACKING_ATTACKER: { '0': ['2'], '1': ['0'], '2':['1','0','2']},
  THREE_CYCLE_ONE_DEFENSE_SELF_ATTACKING_DEFENDER: { '0': ['2','0'], '1': ['0'], '2':['1','0']},
  THREE_CYCLE_ONE_DEFENSE_SELF_ATTACKING_BYSTANDER: { '0': ['2'], '1': ['0','1'], '2':['1','0']},
  THREE_CYCLE_ONE_DEFENSE_SELF_ATTACKING_ATTACKER_AND_DEFENDER: { '0': ['2','0'], '1': ['0'], '2':['1','0','2']},
  THREE_CYCLE_ONE_DEFENSE_SELF_ATTACKING_ATTACKER_AND_BYSTANDER: { '0': ['2'], '1': ['0','1'], '2':['1','0','2']},
  THREE_CYCLE_ONE_DEFENSE_SELF_ATTACKING_DEFENDER_AND_BYSTANDER: { '0': ['2','0'], '1': ['0','1'], '2':['1','0']},
  THREE_CYCLE_ONE_DEFENSE_SELF_ATTACKING_ALL: { '0': ['2','0'], '1': ['0','1'], '2':['1','0','2']},
  THREE_RING_SYMMETERIC_ATTACKING: { '0': ['2'], '1': ['0','2'], '2':['0']},
  THREE_RING_SYMMETERIC_ATTACKING_SELF_ATTACKING_TARGET: { '0': ['2'], '1': ['0','1','2'], '2':['0']},
  THREE_RING_SYMMETERIC_ATTACKING_SELF_ATTACKING_ATTACKER: { '0': ['2','0'], '1': ['0','2'], '2':['0']},
  THREE_RING_SYMMETERIC_ATTACKING_SELF_ATTACKING_TARGET_ATTACKER: { '0': ['2','0'], '1': ['0','1','2'], '2':['0']},
  THREE_RING_SYMMETERIC_ATTACKING_SELF_ATTACKING_ATTACKERS: { '0': ['2','0'], '1': ['0','2'], '2':['0','2']},
  THREE_RING_SYMMETERIC_ATTACKING_SELF_ATTACKING_ALL: { '0': ['2','0'], '1': ['0','1','2'], '2':['0','2']},
  THREE_CYCLE_TWO_DEFENSES: { '0': ['2'], '1': ['0','2'], '2':['1','0']},
  THREE_CYCLE_TWO_DEFENSES_SELF_ATTACKING_ATTACKED: { '0': ['2'], '1': ['0','1','2'], '2':['1','0']},
  THREE_CYCLE_TWO_DEFENSES_SELF_ATTACKING_ATTACKER: { '0': ['2','0'], '1': ['0','2'], '2':['1','0']},
  THREE_CYCLE_TWO_DEFENSES_SELF_ATTACKING_MIDDLE: { '0': ['2'], '1': ['0','2'], '2':['1','0','2']},
  THREE_CYCLE_TWO_DEFENSES_SELF_ATTACKING_OUTSIDES: { '0': ['2','0'], '1': ['0','1','2'], '2':['1','0']},
  THREE_CYCLE_TWO_DEFENSES_SELF_ATTACKING_MIDDLE_ATTACKER: { '0': ['2','0'], '1': ['0','2'], '2':['1','0','2']},
  THREE_CYCLE_TWO_DEFENSES_SELF_ATTACKING_MIDDLE_ATTACKED: { '0': ['2'], '1': ['0','1','2'], '2':['1','0','2']},
  THREE_CYCLE_TWO_DEFENSES_SELF_ATTACKING_ALL: { '0': ['2','0'], '1': ['0','1','2'], '2':['1','0','2']},
  THREE_CYCLE_DEFENDED: { '0': ['2','1'], '1': ['0','2'], '2':['1','0']},
  THREE_CYCLE_DEFENDED_ONE_SELF_ATTACKING: { '0': ['2','0','1'], '1': ['0','2'], '2':['1','0']},
  THREE_CYCLE_DEFENDED_TWO_SELF_ATTACKING: { '0': ['2','0','1'], '1': ['0','1','2'], '2':['1','0']},
  THREE_CYCLE_DEFENDED_ALL_SELF_ATTACKING: { '0': ['2','0','1'], '1': ['0','1','2'], '2':['1','0','2']},
};
